Update Flux CD Git repositoryUpdate

diff --git a/.github/workflows/vm-microservice-CI.yaml b/.github/workflows/vm-microservice-CI.yaml
--- a/.github/workflows/vm-microservice-CI.yaml
+++ b/.github/workflows/vm-microservice-CI.yaml
@@ -37,8 +37,11 @@ jobs:
                 git config --global user.name "vamshireddy24"
                 git clone https://github.com/vamika-store/vamika-backend.git
                 cd vamika-backend
-                ls -R
-                sed -i 's|tag: .*| tag: "$GITHUB_SHA"|' ./charts/vm-microservice/values.yaml
+                if [-f "charts/vm-microservice/values.yaml" ]; then 
+                  sed -i 's|tag: .*| tag: "'"$GITHUB_SHA"'"|' ./charts/vm-microservice/values.yaml
+                else
+                  echo "Error: values.yaml not found!"
+                exit 1
                 fit add charts/vm-microservice/values.yaml
                 git commit -m "Update backend image tag to $GITHUB_SHA"
                 git push
